apiVersion: v1
kind: Service
metadata:
  name: train-schedule-service
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: NodePort
  selector:
    app: train-schedule
  ports:
  - protocol: TCP
    port: 3000
    nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-schedule-deployment
  labels:
    app: train-schedule
spec:
  replicas: 2
  selector:
    matchLabels:
      app: train-schedule
  template:
    metadata:
      labels:
        app: train-schedule
    spec:
      containers:
      - name: train-schedule
        image: ${IMAGE_NAME}:${IMAGE_TAG}
        resources:
          limits:
            cpu: "0.2"
            memory: 512Mi
          requests:
            cpu: "0.1"
            memory: 256Mi
        args:
        - -cpus
        - "0.5"
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          timeoutSeconds: 5
          periodSeconds: 10
      imagePullSecrets:
      - name: train-docker-credentials
